/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as SquadsRouteImport } from './routes/squads'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersServerIdRouteImport } from './routes/servers.$serverId'
import { Route as DmUserIdRouteImport } from './routes/dm.$userId'
import { Route as ClipClipIdRouteImport } from './routes/clip.$clipId'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppTournamentsRouteImport } from './routes/_authenticated/app/tournaments'
import { Route as AuthenticatedAppSquadsRouteImport } from './routes/_authenticated/app/squads'
import { Route as AuthenticatedAppShopRouteImport } from './routes/_authenticated/app/shop'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app/profile'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app/history'
import { Route as AuthenticatedAppFriendsRouteImport } from './routes/_authenticated/app/friends'
import { Route as AuthenticatedAppFeedRouteImport } from './routes/_authenticated/app/feed'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app/admin'
import { Route as AuthenticatedAppServersServerIdRouteImport } from './routes/_authenticated/app/servers.$serverId'
import { Route as AuthenticatedAppDmUserIdRouteImport } from './routes/_authenticated/app/dm.$userId'
import { Route as AuthenticatedAppClipClipIdRouteImport } from './routes/_authenticated/app/clip.$clipId'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsRoute = SquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const DmUserIdRoute = DmUserIdRouteImport.update({
  id: '/dm/$userId',
  path: '/dm/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipClipIdRoute = ClipClipIdRouteImport.update({
  id: '/clip/$clipId',
  path: '/clip/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTournamentsRoute =
  AuthenticatedAppTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSquadsRoute = AuthenticatedAppSquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppShopRoute = AuthenticatedAppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFriendsRoute = AuthenticatedAppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFeedRoute = AuthenticatedAppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppServersServerIdRoute =
  AuthenticatedAppServersServerIdRouteImport.update({
    id: '/servers/$serverId',
    path: '/servers/$serverId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDmUserIdRoute =
  AuthenticatedAppDmUserIdRouteImport.update({
    id: '/dm/$userId',
    path: '/dm/$userId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClipClipIdRoute =
  AuthenticatedAppClipClipIdRouteImport.update({
    id: '/clip/$clipId',
    path: '/clip/$clipId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/squads': typeof SquadsRoute
  '/tournaments': typeof TournamentsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/clip/$clipId': typeof ClipClipIdRoute
  '/dm/$userId': typeof DmUserIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/app/squads': typeof AuthenticatedAppSquadsRoute
  '/app/tournaments': typeof AuthenticatedAppTournamentsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/clip/$clipId': typeof AuthenticatedAppClipClipIdRoute
  '/app/dm/$userId': typeof AuthenticatedAppDmUserIdRoute
  '/app/servers/$serverId': typeof AuthenticatedAppServersServerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/squads': typeof SquadsRoute
  '/tournaments': typeof TournamentsRoute
  '/clip/$clipId': typeof ClipClipIdRoute
  '/dm/$userId': typeof DmUserIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/friends': typeof AuthenticatedAppFriendsRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/app/squads': typeof AuthenticatedAppSquadsRoute
  '/app/tournaments': typeof AuthenticatedAppTournamentsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/clip/$clipId': typeof AuthenticatedAppClipClipIdRoute
  '/app/dm/$userId': typeof AuthenticatedAppDmUserIdRoute
  '/app/servers/$serverId': typeof AuthenticatedAppServersServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/squads': typeof SquadsRoute
  '/tournaments': typeof TournamentsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/clip/$clipId': typeof ClipClipIdRoute
  '/dm/$userId': typeof DmUserIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/feed': typeof AuthenticatedAppFeedRoute
  '/_authenticated/app/friends': typeof AuthenticatedAppFriendsRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/shop': typeof AuthenticatedAppShopRoute
  '/_authenticated/app/squads': typeof AuthenticatedAppSquadsRoute
  '/_authenticated/app/tournaments': typeof AuthenticatedAppTournamentsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/clip/$clipId': typeof AuthenticatedAppClipClipIdRoute
  '/_authenticated/app/dm/$userId': typeof AuthenticatedAppDmUserIdRoute
  '/_authenticated/app/servers/$serverId': typeof AuthenticatedAppServersServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feed'
    | '/friends'
    | '/history'
    | '/login'
    | '/profile'
    | '/shop'
    | '/squads'
    | '/tournaments'
    | '/app'
    | '/clip/$clipId'
    | '/dm/$userId'
    | '/servers/$serverId'
    | '/app/admin'
    | '/app/feed'
    | '/app/friends'
    | '/app/history'
    | '/app/profile'
    | '/app/shop'
    | '/app/squads'
    | '/app/tournaments'
    | '/app/'
    | '/app/clip/$clipId'
    | '/app/dm/$userId'
    | '/app/servers/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/feed'
    | '/friends'
    | '/history'
    | '/login'
    | '/profile'
    | '/shop'
    | '/squads'
    | '/tournaments'
    | '/clip/$clipId'
    | '/dm/$userId'
    | '/servers/$serverId'
    | '/app/admin'
    | '/app/feed'
    | '/app/friends'
    | '/app/history'
    | '/app/profile'
    | '/app/shop'
    | '/app/squads'
    | '/app/tournaments'
    | '/app'
    | '/app/clip/$clipId'
    | '/app/dm/$userId'
    | '/app/servers/$serverId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/feed'
    | '/friends'
    | '/history'
    | '/login'
    | '/profile'
    | '/shop'
    | '/squads'
    | '/tournaments'
    | '/_authenticated/app'
    | '/clip/$clipId'
    | '/dm/$userId'
    | '/servers/$serverId'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/feed'
    | '/_authenticated/app/friends'
    | '/_authenticated/app/history'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/shop'
    | '/_authenticated/app/squads'
    | '/_authenticated/app/tournaments'
    | '/_authenticated/app/'
    | '/_authenticated/app/clip/$clipId'
    | '/_authenticated/app/dm/$userId'
    | '/_authenticated/app/servers/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  FeedRoute: typeof FeedRoute
  FriendsRoute: typeof FriendsRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  SquadsRoute: typeof SquadsRoute
  TournamentsRoute: typeof TournamentsRoute
  ClipClipIdRoute: typeof ClipClipIdRoute
  DmUserIdRoute: typeof DmUserIdRoute
  ServersServerIdRoute: typeof ServersServerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads': {
      id: '/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof SquadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$userId': {
      id: '/dm/$userId'
      path: '/dm/$userId'
      fullPath: '/dm/$userId'
      preLoaderRoute: typeof DmUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip/$clipId': {
      id: '/clip/$clipId'
      path: '/clip/$clipId'
      fullPath: '/clip/$clipId'
      preLoaderRoute: typeof ClipClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tournaments': {
      id: '/_authenticated/app/tournaments'
      path: '/tournaments'
      fullPath: '/app/tournaments'
      preLoaderRoute: typeof AuthenticatedAppTournamentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/squads': {
      id: '/_authenticated/app/squads'
      path: '/squads'
      fullPath: '/app/squads'
      preLoaderRoute: typeof AuthenticatedAppSquadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/shop': {
      id: '/_authenticated/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AuthenticatedAppShopRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/friends': {
      id: '/_authenticated/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AuthenticatedAppFriendsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/feed': {
      id: '/_authenticated/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AuthenticatedAppFeedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/servers/$serverId': {
      id: '/_authenticated/app/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/app/servers/$serverId'
      preLoaderRoute: typeof AuthenticatedAppServersServerIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dm/$userId': {
      id: '/_authenticated/app/dm/$userId'
      path: '/dm/$userId'
      fullPath: '/app/dm/$userId'
      preLoaderRoute: typeof AuthenticatedAppDmUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clip/$clipId': {
      id: '/_authenticated/app/clip/$clipId'
      path: '/clip/$clipId'
      fullPath: '/app/clip/$clipId'
      preLoaderRoute: typeof AuthenticatedAppClipClipIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppFeedRoute: typeof AuthenticatedAppFeedRoute
  AuthenticatedAppFriendsRoute: typeof AuthenticatedAppFriendsRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppShopRoute: typeof AuthenticatedAppShopRoute
  AuthenticatedAppSquadsRoute: typeof AuthenticatedAppSquadsRoute
  AuthenticatedAppTournamentsRoute: typeof AuthenticatedAppTournamentsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppClipClipIdRoute: typeof AuthenticatedAppClipClipIdRoute
  AuthenticatedAppDmUserIdRoute: typeof AuthenticatedAppDmUserIdRoute
  AuthenticatedAppServersServerIdRoute: typeof AuthenticatedAppServersServerIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppFeedRoute: AuthenticatedAppFeedRoute,
  AuthenticatedAppFriendsRoute: AuthenticatedAppFriendsRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppShopRoute: AuthenticatedAppShopRoute,
  AuthenticatedAppSquadsRoute: AuthenticatedAppSquadsRoute,
  AuthenticatedAppTournamentsRoute: AuthenticatedAppTournamentsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppClipClipIdRoute: AuthenticatedAppClipClipIdRoute,
  AuthenticatedAppDmUserIdRoute: AuthenticatedAppDmUserIdRoute,
  AuthenticatedAppServersServerIdRoute: AuthenticatedAppServersServerIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  FeedRoute: FeedRoute,
  FriendsRoute: FriendsRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  SquadsRoute: SquadsRoute,
  TournamentsRoute: TournamentsRoute,
  ClipClipIdRoute: ClipClipIdRoute,
  DmUserIdRoute: DmUserIdRoute,
  ServersServerIdRoute: ServersServerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
